image: gitpod/workspace-python  # Base image with Python pre-installed

tasks:
  - name: Set up .venv and install dependencies
    init: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    command: echo "✅ .venv environment ready and dependencies installed"

vscode:
  extensions:
    - ms-python.python
