image: gitpod/workspace-python

tasks:
  - name: Create .venv and install dependencies
    init: |
      python3 -m venv .venv
      . .venv/bin/activate
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    command: echo "✅ Entorno virtual y dependencias listos"

vscode:
  extensions:
    - ms-python.python
